// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGRXnC0G6CLhwuFkyqLcwfGnsTD2ZNteY',
    appId: '1:479399907675:web:320b0c9c6026a0ce1d8a7e',
    messagingSenderId: '479399907675',
    projectId: 'flutter-projects-811c2',
    authDomain: 'flutter-projects-811c2.firebaseapp.com',
    storageBucket: 'flutter-projects-811c2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA--lmB9D-2Oll3OvrbC2ggyRzS48aZweA',
    appId: '1:479399907675:android:5908d5930700ff981d8a7e',
    messagingSenderId: '479399907675',
    projectId: 'flutter-projects-811c2',
    storageBucket: 'flutter-projects-811c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNLHyQtvtNCxsNAtO4QYPt5oPMhGRUZ_A',
    appId: '1:479399907675:ios:7314eaeafb9b9e0a1d8a7e',
    messagingSenderId: '479399907675',
    projectId: 'flutter-projects-811c2',
    storageBucket: 'flutter-projects-811c2.appspot.com',
    iosClientId: '479399907675-jhpdtkvbn3a8hpqvkm2t24hidkr8bbcl.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushApp',
  );
}
